### ISSUE TITLE
In widget, if I choose only to show today's events & tasks, I still get tasks for tomorrow.  

### ISSUE THREAD

**Issue by kyledev80020** [andstatus/todoagenda#102]
I am using tasks.org, and it appears to be related to the "start time"

If today is Monday, and I have a task due on Wednesday that starts "day before due" (aka Tuesday) then it shows up on Monday's Todo-agenda.

If I change the task to be Due on Tuesday, and Start on Tuesday, then it does not show up on Monday, correctly, but does still on Tuesday.  So it's only the tasks that have the start date "Day before due" that show up inappropriately.

**Comment by yvolk** [comment]
In order to debug this I go to Settings -> Feedback and Backup and click "Share events and settings for debugging" and getting this JSON file for tests: 
[tomorrows_tasks.zip](https://github.com/andstatus/todoagenda/files/10246193/tomorrows_tasks.zip)
Testing this...

**Comment by yvolk** [comment]
@kyledev80020 A year passed, I returned to this case again... And I still cannot reproduce the problem that you noticed.
Now I can only suggest that a problem may be caused by differences in time zones for different events (tasks in this case).
Anyway, in order to give an answer (and a fix, if necessary) I need to see your  JSON file created in the widget's settings -> Feedback and Backup -> Share events and settings for debugging.

**Comment by yvolk** [comment]
@kyledev80020 Thank you again for the report. 
At last I resolved the problem by decreasing endOfTimeRange filter's time by 1 millisecond (so tomorrow's events at 00:00 won't get into the list.
This is a corner case that wasn't noticed for years.
None of existing tests failed, so I think that the change is relatively safe, although some users may notice the difference :-)
