### ISSUE TITLE
Todoagenda don't detect my tasks synch with davx

### ISSUE THREAD

**Issue by Djey51** [andstatus/todoagenda#110]
Hi,
Todoagenda don't detect my tasks synch with davx.
I'm using JTX board as tasks application. Jtx synch my tasks from davx5.
Could you help le please?
Thanks

**Comment by yvolk** [comment]
Probably your tasks app isn't supported.
Please read a note on tasks support and see links in the Features section of Readme: https://github.com/andstatus/todoagenda

**Comment by yvolk** [comment]
> Would it be possible to support [jtx Board](https://github.com/TechbeeAT/jtxBoard) in the future?

I see it's Open Source. 
Does it have any third party widget that supports the app? (So I could lookup a way to integrate with it)

**Comment by qoheniac** [comment]
I don't know about any 3rd party widget but the app itself provides a widget if that helps anything: https://github.com/TechbeeAT/jtxBoard/tree/develop/app/src/main/java/at/techbee/jtx/widgets

**Comment by yvolk** [comment]
@qoheniac I asked developers of that app about a way to work with third party widgets https://github.com/TechbeeAT/jtxBoard/issues/845

**Comment by SanskritFritz** [comment]
I too use jtx Board with Davx5. Having also Tasks installed and configured to sync with the same Davx5 container, and since Tasks is suppoted by Todoagenda, eventually all tasks from jtx show up there. Just a workaround :)

**Comment by gbakeman** [comment]
I'm another user who got rid of OpenTasks after realizing that it appears to be abandoned. Imagine my surprise when Todoagenda stops showing my task lists after removing OpenTasks 😅

JTX appears to be the latest and greatest supported by DAVx5. I'm sure this has been investigated before, but why can't TodoAgenda communicate directly with DAVx5 for task data rather than relying on these intermediary apps to function?
