### ISSUE TITLE
4.8.0: New events are not shown up

### ISSUE THREAD

**Issue by jakobroehrl** [andstatus/todoagenda#131]
After the new version new events are not shown up in the widget, the reload button has no effect.
In my calendar app I see the events.
When I restart the smartphone the events are shown.
When I create a new widget the new events are shown, too.

**Comment by yvolk** [comment]
Hello @jakobroehrl 
I just tested this version on my Android 14 device.
I added an event in Google Calendar and waited for about a minute. Then I saw the newly added event even without any Refresh buttons.
Probably the problem is not in the new version of the widget.

Please look for solutions in this thread: https://github.com/andstatus/todoagenda/issues/17
And maybe here: https://github.com/andstatus/todoagenda/issues/45
Above links are in the Troubleshooting section: https://github.com/andstatus/todoagenda#troubleshooting )

**Comment by jakobroehrl** [comment]
Error on my side, thanks a lot.
