### ISSUE TITLE
Add support for "Tasks: Astrid To-Do List Clone"

### ISSUE THREAD

**Issue by yvolk** [andstatus/todoagenda#2]
There is a long outstanding need to integrate our Widget with Google Tasks (see e.g. https://github.com/plusonelabs/calendar-widget/issues/29 ).

Astrid To-Do List Clone ( https://github.com/tasks/tasks ) is integrated with Google Tasks, and so we could try to integrate our widget with it and thus get integration with google tasks.

I found some info on possible widget integration with Astrid: tasks/tasks#817 and also contacted with its developer. As @abaker wrote me the app does expose a content provider to read some basic task information. This content provider was originally from Astrid Tasks, and the Pure Calendar Widget app is using it: https://github.com/tasks/tasks/blob/3d89511a1886ac5fbdce38e91e64ed289c6a8ab3/app/src/main/java/com/todoroo/astrid/provider/Astrid2TaskProvider.java

**Comment by ekalin** [comment]
Integration with Tasks (Astrid clone) would be a nice feature. It seems a popular app, and also syncs with Google Tasks and CalDAV.

The content provider works, but has some limitations:

It ignores what is passed to it (projection, query, where, etc) and always returns the results of a fixed query. Filtering (by date and task list) would need to be done on the calling class, but that shouldn't be a problem.

The start date (called Hide until in the app) is not returned. Instead, hidden tasks (their "Hide until" is after now) are not returned. This might be a more serious limitation. (However, the concept is slightly different - the app by default does not display hidden tasks, instead of displaying tasks later as other task managers do for tasks with a start date in the future.)

It should be simple to change Tasks to return this date, but it would change the behavior for any existing consumer of the content provider, since tasks that are currently hidden would suddenly appear. In practice I'm not sure this is a problem, the author is only aware of Pure Calendar Widget, which hasn't had new development for a while, and the last version was buggy when I stopped using it.

The current query could be kept, and a new one could be added, but this increased the maintenance burden, I'm not sure if the author would be willing to do that.

Anyway, even in the current state, integration should be relatively simple.

**Comment by abaker** [comment]
I'm willing to create a new content provider if the existing one is insufficient

**Comment by yvolk** [comment]
Hello @abaker!
I created initial implementation of your app's support in the ToDo Agenda widget. It already can show tasks from your app (that I built from sources from master branch), but due to above mentioned provider (and app's...) limitations is too primitive yet to be usable.
Please see this class, it contains my comments with TODO comments mentioning places in your app (content provider) that need to be improved: https://github.com/andstatus/todoagenda/blob/feature/2-support-astrid-clone/app/src/main/java/org/andstatus/todoagenda/task/astrid/AstridCloneTasksProvider.java

This is just the first iteration, so please don't consider it to be the final API. Moreover, Tasks support in the "ToDo Agenda" widget is quite basic, so I expect to extend it (and hence may need e.g. additional data and API endpoints, e.g. an intent to ADD new task.

It's up to you, of course, whether to extend existing provider or create a new one... 

@abaker Your move!

![Screenshot_1583775313](https://user-images.githubusercontent.com/207716/76241716-74800080-6246-11ea-97f3-45694b99e193.png)

**Comment by yvolk** [comment]
ToDo Agenda v.4.1.0 with support of the "Tasks: Astrid To-Do List Clone" is released today. See #3 for download options.
The support is not announced yet, because the Tasks app with corresponding changes is not released yet.

@abaker

**Comment by yvolk** [comment]
Implemented in v.4.2.0 #3

**Comment by Torenga** [comment]
I tested out Todo Agenda after Tasks: Astrid To-Do List Clone dropped v10 and mentioned Todo Agenda in the release notes. What a great widget that combines both calendar and tasks, just what I've been looking for!

There is one issue that currently is stopping me from using Todo Agenda as my daily overview - All day tasks.

Most of my tasks are assigned to "All day" in Tasks: Astrid To-Do List Clone and are correctly displayed in their own section at the bottom of the agenda in the Tasks app. But they show up at noon, 12.00, in Todo Agenda!

When assigned a due _time_ they show up in the correct location compared to calendar entries. This is really confusing when trying to get a quick overview of today's tasks and meetings - Have I set the due time at 12.00 exactly or are they "all day, unassigned time" and just show up at noon?

I request that all day tasks without a specific due time is shown (in order of preference)
-At the top of today's agenda
-At the bottom of todays agenda
-At the top of "dateless" task list at the very botton
-Not at all until assigned a proper time

And that tasks with due date but without due time is marked as such, perhaps with an "All day" tag/text.

Thank you for your consideration!

**Comment by yvolk** [comment]
Thank you for the review @Torenga. Fortunately, you are not the first, who noticed that tasks without start and due dates should be placed in some predefined place or maybe even hidden. And we do have "Tasks without start and due dates" setting in "Event filters" section allowing a User to make their choice. More details and examples in: #4

**Comment by abaker** [comment]
This is likely due to the way Tasks denotes all-day events. This is behavior carried over from Astrid that I haven't addressed yet.

A task is considered all day if the timestamp's seconds and milliseconds are 0 ([source](https://github.com/tasks/tasks/blob/daef79eb66973e8d981419e89edf48fd4696ed0b/app/src/main/java/com/todoroo/astrid/data/Task.kt#L614)). 

Additionally, tasks without due times are assigned a time of 12:00:00 ([source](https://github.com/tasks/tasks/blob/daef79eb66973e8d981419e89edf48fd4696ed0b/app/src/main/java/com/todoroo/astrid/data/Task.kt#L602)). I'm not sure what the rationale was for this behavior, but I think it was so that all-day events would be sorted between morning and afternoon events

**Comment by yvolk** [comment]
@abaker Thank you for clarifications and links. This means that in addition to changes in integration code between our apps we need to do some conceptual changes in ToDo Agenda:
1. Add "All day task" support. This is easy as we do have "All day Calendar events"
2. Add "Event (Calendar event or Task) with date but without time. We don't have such a notion yet in our app. Thinking about existing Calendar events' cases I see that "Birthday" is actually an event without time, and not "all day event" as it is now. The problem is that there is no way (or I don't know it...) to distinguish such events...

**Comment by abaker** [comment]
Sorry, the way I phrased that made it sound like I was talking about two separate concepts. Tasks doesn't have a concept of 'all day', I was just using that term to describe tasks with a due date but no time

**Comment by yvolk** [comment]
@abaker Aha, thanks. That is easier.

**Comment by yvolk** [comment]
@abaker @Torenga I added support of "All day tasks" to ToDo Agenda. so now All day task is shown at midnight.
For ordering and visualization of all day events (including All day tasks) I created a separate issue: #48

**Comment by yvolk** [comment]
The fix released to Beta channel, see #3

**Comment by Torenga** [comment]
Currently tasks in the same time slot (All day or at a certain time) are sorted alphabetically, leading to high priority tasks often being displayed below lower priority tasks.

I would prefer to have the option for them to be sorted by priority first, then alphabetically.

**Comment by yvolk** [comment]
@Torenga Thank for suggestion, I created a separate issue for "priority": https://github.com/andstatus/todoagenda/issues/50
