### ISSUE TITLE
Events from one of my calendars not displaying in app

### ISSUE THREAD

**Issue by camoorejr** [andstatus/todoagenda#35]
I have two work calendars that I have added to my google calendar. I can see events for both in google calendar on my phone and on the computer. However, on the Todo agenda app only one of these calendars shows up. No idea why I can't get events for the second one to display.

**Comment by yvolk** [comment]
ToDo Agenda app and Google Calendar app on the same Android device use different means to get calendar events.
ToDo Agenda uses "Calendar provider" Android service, working on this device whereas Google Calendar probably syncs with Google cloud directly. So different results are usually caused by Android "Calendar provider" sync problems, which may require user-forced re-syncing. 
More details on fixing sync issues are here: https://github.com/andstatus/todoagenda/issues/17
