### ISSUE TITLE
Error message when touched an empty list entry after a list of events

### ISSUE THREAD

**Issue by d33tah** [andstatus/todoagenda#36]
![bug](https://user-images.githubusercontent.com/295322/89057467-fd1a4d00-d35d-11ea-80a6-db9e47cffc27.png)

Installed on latest LineageOS from today's snapshot of F-Droid. Phone has only very basic Google Apps support - Google Calendar is IIRC not there.

**Comment by yvolk** [comment]
@d33tah Does "ToDo Agenda" allows you to see any events?
I mean does this problem that you are reporting occur only if you tap on empty space, but otherwise the Widget works normally?

**Comment by yvolk** [comment]
@d33tah Thank for reporting. This appeared an old bug that doesn't occur on older Android devices (e.g. on Android 7.0)
The bug became apparent in v.4.1.1 of our widget, because instead of silent errors I started to catch them and open the error screen that you noticed.
Fixed. Now the widget's settings are opened on the touch/click.

**Comment by yvolk** [comment]
Fixed in v.4.2.0 #3
