### ISSUE TITLE
Show correctly STATUS:CANCELLED event

### ISSUE THREAD

**Issue by Spheerys** [andstatus/todoagenda#51]
Hi,

I have the use of the Canceled status for some events on a distant .ics file
The code on the event is : 
```
STATUS:CANCELLED
```
But todoagenda don't show these events differently than the normal ones.

Could it be possible to show the canceled events striped ?

**Comment by yvolk** [comment]
Hi @Spheerys , we have a request to Filter tasks by status, so cancelled tasks won't be shown at all #8 
As I understand, you would prefer to see cancelled tasks, but visually easily distinguished from other tasks?!

Could you attach a screenshot / picture: how exactly do you think cancelled tasks should be  shown in the widget?

**Comment by RobertZenz** [comment]
Having the event text in strikethrough would be the traditional method of showing cancelled events. That way you still see the event, you can still read it but it is clearly visible that it is cancelled.

**Comment by Spheerys** [comment]
IMHO the best way to integrate this is to mark by default the deleted events with a strikethrough, but also an option on the settings to completely hide the canceled events :)

**Comment by rufuswilson** [comment]
I would very much like this enhancement.

There is also the case where the event with multiple guests is not cancelled but I/the user would have declined the invite.

**Comment by sphh** [comment]
Thanks @feilen to implement the styles for cancelled and tentative events!

I also miss the possibility to filter events based on their status. Especially I am looking for a filter to hide cancelled events (because I only have limited screen space). @feilen mentioned in his PR [#82](https://github.com/andstatus/todoagenda/pull/82#issue-1029783735)  that as an added bonus, it makes it pretty easy to resolve #8 [Filter tasks and events by status]. Is this added bonus planed?

**Comment by yvolk** [comment]
We have a separate ticket for filtering, as you noticed. So closing this as done.
