### ISSUE TITLE
"Add task" button doesn't work for  for tasks.org app

### ISSUE THREAD

**Issue by DonPicciotto** [andstatus/todoagenda#53]
Sadly the button for a new task doesn't seems to work with tasks.org app, despite the new integration with DAVx5. Please, consider adding support for that app as well

**Comment by yvolk** [comment]
Hi @DonPicciotto 
"Add Task" button was added specifically for tasks.org v.10+ app.
Please see https://github.com/andstatus/todoagenda/issues/9 
If in your case the button doesn't work, this could be just general widget problem of not working buttons, see https://github.com/andstatus/todoagenda/issues/45 in that case.

Otherwise we need much more info about your case in order to start thinking of any fix...

**Comment by DonPicciotto** [comment]
Sorry, my mistake, I should at least read what is written on the main page... I solved just uninstalling and reinstalling the widget, after proper configuration of davx and tasks.org

**Comment by yvolk** [comment]
@DonPicciotto Thank you for the feedback!
