### ISSUE TITLE
How to change Calendar's Default color

### ISSUE THREAD

**Issue by yvolk** [andstatus/todoagenda#6]
Looks like the easiest way to change a calendar's default color is in the Google Calendar App settings. I just tried!
See a screenshot in section 4 of https://www.computerworld.com/article/3390992/google-calendar-android.html
and below:
![63638602-339e1100-c693-11e9-8ac1-bbe75eb0a4be](https://user-images.githubusercontent.com/207716/73589712-0e87b700-44eb-11ea-8b19-6c0670211602.png)

Conclusion: Default Calendar color and colors of individual Calendar events should be set in the source Calendar app (see above example with Google Calendar). There is no need to duplicate it in this Widget.

The same applies to Tasks: Open Tasks app does have this feature also.

**Comment by KrisadaFantasy** [comment]
You can also use **Calendar Color** ([Github](https://github.com/pascalfree/calendar-color) | [F-Droid](https://f-droid.org/en/packages/ch.ihdg.calendarcolor/)). Still working greta on my Android 13-based HyperOS.

In my case, I use Outlook calendar but To Do Agenda refer to colour in Google Calendar, which list my Outlook calendar as "on this device" calendar without colour option since it's non-Google, and randomly assign colour I don't like. **Calendar Color** app can change colour of any calendar in your device including non-google one.
