### ISSUE TITLE
Event list not refreshed

### ISSUE THREAD

**Issue by dagord** [andstatus/todoagenda#72]
Hello
I was happily using the app for several months, until some days ago.
Suddenly, the event list is no more refresehd, as it is stuck on last friday: if I reboot the phone (Redmi Note 7) the widget gets refreshed, then it stucks again.
I just can see the first few events in the list... if I try to scroll it down, I get the "loading" message instead of the events title.

What I tried:
- I double checked the sync settings as suggested on issue #17 
- I double checked ToDo permissions
- I removed and re-installed Google Calendar app
- I checked/unchecked calendars from ToDo settings

None of them seems to work

**Comment by yvolk** [comment]
Hi @dagord The problem probably occurred due to an update of some app or your device's system update.
Getting "loading..." messages makes me think that there maybe a problem with our widget's interaction with your device's Launcher app.
Which launcher are you using? 
Please try to change it, e.g. switch from custom Launcher to the device's default one or vice versa.

In the old widget's issues list I found a couple of similar reports, please see:
https://github.com/plusonelabs/calendar-widget/issues/279
https://github.com/plusonelabs/calendar-widget/issues/318

?!

**Comment by dagord** [comment]
Hello @yvolk ,
thank you for your reply.
I'll try your suggestion but I confirm that on my side there wasn't any change/update that I'm aware of. Currently I'm using Poco Launcher, which was updated to the last version more than a month ago.
In case this helps: I tried to check/uncheck more calendars on the ToDo settings, but the event list doesn't change

**Comment by dagord** [comment]
Some more info: changing any setting (style, font size, colors and so on...) actually doesn't have any effect! The widget is "stuck"!

**Comment by yvolk** [comment]
This looks more like incompatibility with the Launcher

**Comment by dagord** [comment]
Hello.
I tried to switch back to the default launcher and the app works!
By the way, I don't know if it's a solution since, as I said, on the other launcher it simply stopped working all of a sudden.

**Comment by yvolk** [comment]
I remember that I struggled with similar problems a couple of years ago, and although I solved the problem at that time (at least for the majority of launchers, including default launchers and Nova launcher) I still have a feeling that this part is not strictly enough described/ defined in Android, and hence prone to compatibility problems...

**Comment by yvolk** [comment]
This ticket is about fixing this problem in 2019: https://github.com/plusonelabs/calendar-widget/issues/318

**Comment by yvolk** [comment]
@dagord You could point your launcher's developers to this thread, maybe they could fix at their side taking into account that our widget works with most of other launchers?!

**Comment by dagord** [comment]
Hi. Brief update: after a few days with the default launcher, the widget is
stuck again, with the same behaviour as described in the previous posts.

Inviato da Android

Il mar 6 lug 2021, 16:53 Yuri Volkov ***@***.***> ha scritto:

**Comment by yvolk** [comment]
@dagord The source code of the widget is open, you could investigate this problem...
Please reboot your device and look how long it will work for the second time.

For your understanding: this is actually a Launcher app that has "stuck" in the widget's updates, because a Launcher initiates or not those updates. 
A this is a Launcher app that actually redraws a widget. Our Widget app only tells it, what to draw...

**Comment by dagord** [comment]
@yvolk 
I'm not experienced in mobile programming, so I can't investigate the bug.
I'm simply reporting the bug.
But there's an interesting update: I tried to switch back to "Calendar Widget" (https://github.com/plusonelabs/calendar-widget), which I was previously using, and bam! Same bug. So it seems it's something on my device side, even if not related to specific laucher, and without any system update.

**Comment by yvolk** [comment]
@dagord Thank you for the update
